services:

  mysql:
    image: mysql
    container_name: timebank-mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: timebank-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "${PMA_HOST}"
      PMA_PORT: "${PMA_PORT}"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
    depends_on:
      - mysql


  backend_timebank:
    build: ./backend_timebank
    container_name: timebank-backend
    ports:
      - "8000:8000"
    environment:
      TIMEBANK_DATABASE_URL: "${TIMEBANK_DATABASE_URL}"
      SEED_DEFAULT_USERS: "${SEED_DEFAULT_USERS}"
      DEFAULT_ADMIN_EMAIL: "${DEFAULT_ADMIN_EMAIL}"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      DEFAULT_ADMIN_FIRST_NAME: "${DEFAULT_ADMIN_FIRST_NAME}"
      DEFAULT_ADMIN_LAST_NAME: "${DEFAULT_ADMIN_LAST_NAME}"
      DEFAULT_USER_EMAIL: "${DEFAULT_USER_EMAIL}"
      DEFAULT_USER_PASSWORD: "${DEFAULT_USER_PASSWORD}"
      DEFAULT_USER_FIRST_NAME: "${DEFAULT_USER_FIRST_NAME}"
      DEFAULT_USER_LAST_NAME: "${DEFAULT_USER_LAST_NAME}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_PUBLISHABLE_KEY: "${STRIPE_PUBLISHABLE_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      SMTP_EMAIL: "${SMTP_EMAIL}"
      SMTP_PASSWORD: "${GMAIL_APP_PWD}"
      FRONTEND_URL: "${FRONTEND_URL}"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure


  backend_payments:
    build: ./backend_payments
    container_name: payments-backend
    ports:
      - "8001:8001"
    environment:
      PAYMENTS_DATABASE_URL: "${PAYMENTS_DATABASE_URL}"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure


  frontend:
    build: ./frontend
    container_name: timebank-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend_timebank
      - backend_payments


volumes:
  mysql_data:
