services:

  mysql:
    image: mysql
    container_name: timebank-mysql
    environment:
      MYSQL_DATABASE: timebank
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: timebank-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 'root'
    depends_on:
      - mysql


  backend_timebank:
    build: ./backend_timebank
    container_name: timebank-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:root@mysql:3306/timebank"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure


  backend_payments:
    build: ./backend_payments
    container_name: payments-backend
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "mysql+pymysql://root:root@mysql:3306/payments"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure


  frontend:
    build: ./frontend
    container_name: timebank-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend_timebank
      - backend_payments


volumes:
  mysql_data:
