awk '
/^\/\* ─── Buttons ──/ {
  print "/* ─── Buttons ───────────────────────────────────────── */"
  print ".btn {"
  print "  width: 100%;"
  print "  padding: 12px 20px;"
  print "  border: 1px solid var(--green);"
  print "  border-radius: var(--radius-sm);"
  print "  font-size: 0.95rem;"
  print "  font-weight: 600;"
  print "  font-family: inherit;"
  print "  cursor: pointer;"
  print "  transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);"
  print "  background: var(--green);"
  print "  color: #ffffff;"
  print "  margin-top: 8px;"
  print "  display: flex;"
  print "  align-items: center;"
  print "  justify-content: center;"
  print "  gap: 8px;"
  print "}"
  print ""
  print ".btn:hover:not(:disabled) {"
  print "  background: var(--green-hover);"
  print "  border-color: var(--green-hover);"
  print "  transform: translateY(-2px);"
  print "  box-shadow: 0 6px 20px rgba(29, 191, 115, 0.25);"
  print "}"
  print ""
  print ".btn:active:not(:disabled) {"
  print "  transform: translateY(0);"
  print "}"
  print ""
  print ".btn:disabled {"
  print "  opacity: 0.5;"
  print "  cursor: not-allowed;"
  print "  filter: grayscale(0.5);"
  print "}"
  print ""
  print ".btn-primary {"
  print "  background: var(--green);"
  print "  border: 1px solid var(--green);"
  print "  color: #ffffff;"
  print "}"
  print ""
  print ".btn-danger {"
  print "  background: rgba(239, 68, 68, 0.1);"
  print "  border: 1px solid rgba(239, 68, 68, 0.2);"
  print "  color: var(--danger-hover);"
  print "}"
  print ""
  print ".btn-danger:hover:not(:disabled) {"
  print "  background: var(--danger);"
  print "  color: #ffffff;"
  print "  border-color: var(--danger);"
  print "  box-shadow: 0 4px 16px rgba(239, 68, 68, 0.3);"
  print "  transform: translateY(-2px);"
  print "}"
  print ""
  print ".btn-success {"
  print "  background: rgba(34, 197, 94, 0.1);"
  print "  border: 1px solid rgba(34, 197, 94, 0.2);"
  print "  color: var(--success-btn);"
  print "}"
  print ""
  print ".btn-success:hover:not(:disabled) {"
  print "  background: var(--success-btn);"
  print "  color: #ffffff;"
  print "  border-color: var(--success-btn);"
  print "  box-shadow: 0 4px 16px rgba(34, 197, 94, 0.3);"
  print "  transform: translateY(-2px);"
  print "}"
  print ""
  print ".btn-refresh, .btn-ghost {"
  print "  background: rgba(255, 255, 255, 0.05);"
  print "  border: 1px solid rgba(255, 255, 255, 0.1);"
  print "  color: var(--text-primary);"
  print "}"
  print ""
  print ".btn-refresh:hover:not(:disabled), .btn-ghost:hover:not(:disabled) {"
  print "  background: rgba(255, 255, 255, 0.1);"
  print "  color: #fff;"
  print "  border-color: rgba(255, 255, 255, 0.2);"
  print "  transform: translateY(-2px);"
  print "}"
  print ""
  skip = 1
}
/^\/\* ─── Info Text ──/ {
  skip = 0
}
!skip { print }
' frontend/src/App.css > tmp.css && mv tmp.css frontend/src/App.css
